### ISSUE TITLE
Unable to prepare route [api/user] for serialization. Uses Closure.

### ISSUE THREAD

**Issue by ted81das** [FusionAuth/fusionauth-example-laravel#6]
Unable to prepare route [api/user] for serialization. Uses Closure.

rtisan:37
      Illuminate\Foundation\Console\Kernel::handle()
[2m+15 vendor frames [22m
    1136|      */
    1137|     public function prepareForSerialization()
    1138|     {
    1139|         if ($this->action['uses'] instanceof Closure) {
  > 1140|             throw new LogicException("Unable to prepare route [{$this->uri}] for serialization. Uses Closure.");
    1141|         }
    1142| 
    1143|         $this->compileRoute();
    1144|
  at vendor/laravel/framework/src/Illuminate/Routing/Route.php:1140

**Comment by mooreds** [comment]
Can you provide a bit more detail? How are you running this? What versions of Laravel, PHP, etc?

Thanks!

**Comment by jobannon** [comment]
@ted81das,

I am closing this issue, due to age outstanding and non-response.  However, please let us know if you have any additional trouble with this tutorial.  We have made several updates recently, so it should be a very functional walk-through!

Thanks!
